version: '3.8'
services:
  typeorm-01:
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: Development
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  typeorm:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3308:3306"